# Generated by Django 3.1 on 2020-11-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('student_name', models.CharField(max_length=255)),
                ('student_id', models.IntegerField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.IntegerField(max_length=20)),
                ('Address', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('tenth', models.CharField(max_length=255)),
                ('twelve', models.CharField(max_length=255)),
                ('cgpa', models.CharField(max_length=255)),
                ('no_backlog', models.IntegerField(max_length=10)),
                ('c_backlog', models.IntegerField(max_length=10)),
            ],
        ),
    ]
