# Generated by Django 3.1 on 2020-11-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appp', '0002_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='c_backlog',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='no_backlog',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(),
        ),
    ]
