# Generated by Django 3.1 on 2020-11-26 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appp', '0003_auto_20201126_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='userid',
        ),
    ]
