# Generated by Django 3.1.3 on 2020-11-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appp', '0004_auto_20201126_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(max_length=255)),
                ('About_company', models.TextField()),
                ('Company_link', models.URLField(max_length=255)),
                ('Jobrole', models.CharField(max_length=255)),
                ('Job_responsilities', models.TextField()),
                ('Job_Salary', models.FloatField(max_length=5)),
                ('Eligibility_cgpa', models.FloatField(max_length=5)),
                ('Eligibility_branches', models.TextField()),
                ('Eligible_Passedout_Batchs', models.CharField(max_length=255)),
                ('Eligibility_education_gap', models.IntegerField()),
                ('application_start_date', models.DateField(null=True)),
                ('application_end_date', models.DateField(null=True)),
            ],
        ),
    ]
