# Generated by Django 3.1 on 2020-12-13 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appp', '0006_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
    ]
